name: CI
on: [pull_request, push]
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        elixir: ["1.7.4", "1.9.1"]
        include:
          - elixir: "1.7.4"
            otp: "20.3.8.23"
          - elixir: "1.9.1"
            otp: "22.x"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Configure git with fake data
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Install Dependencies
        run: mix deps.get
      - name: Check Formatted
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test
